name: Generate Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.2.0)'
        required: true

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Release Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout develop
          git pull
          git checkout -b release/v${{ github.event.inputs.version }}
          git push -u origin release/v${{ github.event.inputs.version }}
      
      - name: Ensure Labels Exist
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Define required labels with their colors and descriptions
            const requiredLabels = [
              {
                name: 'in-progress',
                color: '0052cc',
                description: 'Issue is being worked on in a draft PR'
              },
              {
                name: 'review-ready',
                color: '5319e7',
                description: 'Work is complete and ready for review'
              },
              {
                name: 'merged-to-develop',
                color: '0e8a16',
                description: 'Implementation has been merged to develop'
              },
              {
                name: 'released',
                color: '1d76db',
                description: 'Feature has been released to production'
              }
            ];
            
            // Function to ensure a label exists
            async function ensureLabelExists(labelInfo) {
              try {
                // Try to get the label
                await github.rest.issues.getLabel({
                  owner,
                  repo,
                  name: labelInfo.name
                });
                console.log(`Label ${labelInfo.name} already exists`);
              } catch (error) {
                if (error.status === 404) {
                  // Label doesn't exist, create it
                  try {
                    await github.rest.issues.createLabel({
                      owner,
                      repo,
                      name: labelInfo.name,
                      color: labelInfo.color,
                      description: labelInfo.description
                    });
                    console.log(`Created label ${labelInfo.name}`);
                  } catch (createError) {
                    console.error(`Error creating label ${labelInfo.name}: ${createError.message}`);
                  }
                } else {
                  console.error(`Error checking label ${labelInfo.name}: ${error.message}`);
                }
              }
            }
            
            // Ensure all required labels exist
            for (const label of requiredLabels) {
              await ensureLabelExists(label);
            }
      
      - name: Collect Pending Issues
        id: collect-issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            console.log('Collecting issues with merged-to-develop label');
            
            // Get all issues with 'merged-to-develop' label
            const { data: issues } = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'merged-to-develop'
            });
            
            console.log(`Found ${issues.length} issues with merged-to-develop label`);
            
            // Format issues for PR description
            let issueList = '';
            let issueRefs = '';
            
            issues.forEach(issue => {
              issueList += `- #${issue.number}: ${issue.title}\n`;
              issueRefs += `Fixes #${issue.number}\n`;
              console.log(`Including issue #${issue.number}: ${issue.title}`);
            });
            
            // Return as a stringified JSON object to preserve formatting
            return {
              result: JSON.stringify({ issueList, issueRefs })
            };
      
      - name: Create Release PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const version = '${{ github.event.inputs.version }}';
            
            // Parse the JSON string back to an object
            const { issueList, issueRefs } = JSON.parse(${{ steps.collect-issues.outputs.result }});
            
            console.log(`Creating release PR for version ${version}`);
            
            const body = `# Release v${version}

## Issues included in this release:
${issueList}

## Changelog
[Add release notes here]

${issueRefs}`;
            
            const { data: pr } = await github.rest.pulls.create({
              owner,
              repo,
              title: `Release v${version}`,
              head: `release/v${version}`,
              base: 'main',
              body: body
            });
            
            console.log(`Created release PR #${pr.number}`);
            
            return {
              pr_number: pr.number,
              pr_url: pr.html_url
            };
